### ISSUE TITLE
Support pod topology spread constraints

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#340]
The operator supports affinity (node affinity, pod affinity, pod anti-affinity). To provide more control, consider supporting [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) (topologySpreadConstraints)

**Comment by greglanthier** [comment]
I'm working on an operator that currently relies on **`topologySpreadConstraints`** to aid in scheduling workloads in a more fault tolerant manner.  I would like to transition to using RuntimeComponent CRs to manage the workloads my operator deploys rather than have my operator manage the workloads directly.

How do y'all envision **`topologySpreadConstraints`** would be added to the runtime-component-operator CRD?

Would this follow the same pattern of [`PodSpec`](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec) - in the sense that a `topologySpreadConstraints` stanza would be a sibling of the `affinity` stanza?

Has this work been planned?  Is there any way I can help - either with PRs or with testing?

**Comment by halim-lee** [comment]
Hi @greglanthier, the work has not been planned as of yet since it is an enhancement idea for the future. It will likely be added as `spec.topologySpreadConstraints` in the CR as `spec.affinity` is. I will update this issue as soon as I start implementing it!

**Comment by greglanthier** [comment]
Thanks for the update @halim-lee.

Since our workloads currently rely on **`topologySpreadConstraints`** and we can't transition to runtime-component-operator until it supports I'd be happy to contribute - be that with code or by providing some testing.

I'll keep watching this space for updates.  Thanks again.

**Comment by leochr** [comment]
@greglanthier Support for topology spread constraints is available in Liberty Operator and Runtime Component Operator 1.3.0+

Closing as delivered.
